import raylib as rl
from pyray import FLAG_FULLSCREEN_MODE, FLAG_MSAA_4X_HINT, FLAG_WINDOW_UNDECORATED, FLAG_WINDOW_RESIZABLE, FLAG_VSYNC_HINT, FLAG_WINDOW_UNFOCUSED
from typing import Final

ENGINEVERSION: Final = "0.1.0"
