from pygame.constants import FULLSCREEN, SCALED, RESIZABLE

ENGINEVERSION: str = '1.3.dev1'
DEFAULTSCREENSIZE: tuple = (640, 360)
WINDOWTITLE: str = 'CORP Engine Window'
WINDOWICON = None
FLAGS: int
RUNNING: bool = True
FPS_CAP: int = 60
BACKGROUND_COLOR: tuple = (224, 224, 224)
RESIZABLE = RESIZABLE
SCALED = SCALED
FULLSCREEN = FULLSCREEN | SCALED
